name       : zsh
version    : 5.6.2
release    : 18
source     :
    - https://nchc.dl.sourceforge.net/project/zsh/zsh/5.6.2/zsh-5.6.2.tar.xz : a50bd66c0557e8eca3b8fa24e85d0de533e775d7a22df042da90488623752e9e
license    : MIT
summary    : The Z Shell
component  : system.utils
description: |
    Z shell (zsh) is a Unix shell that can be used as an interactive login shell and powerful command interpreter. It can be viewed as an extended Bourne shell with a number of improvements sourced from bash, tcsh, and ksh.
builddeps  :
    - pkgconfig(libcap)
    - gdbm-devel
setup      : |
    %configure --bindir=/bin \
               --enable-cap \
               --enable-multibyte \
               --enable-pcre \
               --with-tcsetpgrp \
               --enable-fndir=/usr/share/zsh/functions \
               --enable-scriptdir=/usr/share/zsh/scripts
build      : |
    %make
install    : |
    %make_install
    rmdir $installdir/usr/share/zsh/site-functions
check      : |
    # Should investigate why this test fails
    rm Test/A05execution.ztst
    %make check
