name       : zsh
version    : 5.8.0
release    : 23
source     :
    - https://sourceforge.net/projects/zsh/files/zsh/5.8/zsh-5.8.tar.xz/download : dcc4b54cc5565670a65581760261c163d720991f0d06486da61f8d839b52de27
license    : MIT
summary    : The Z Shell
component  : system.utils
description: |
    Z shell (zsh) is a Unix shell that can be used as an interactive login shell and powerful command interpreter. It can be viewed as an extended Bourne shell with a number of improvements sourced from bash, tcsh, and ksh.
builddeps  :
    - pkgconfig(libcap)
    - gdbm-devel
setup      : |
    %configure --bindir=/bin \
               --enable-cap \
               --enable-multibyte \
               --enable-pcre \
               --with-tcsetpgrp \
               --enable-etcdir=/usr/share/defaults/etc/zsh \
               --enable-zshenv=/usr/share/defaults/etc/zsh/zshenv \
               --enable-zlogin=/usr/share/defaults/etc/zsh/zlogin \
               --enable-zlogout=/usr/share/defaults/etc/zsh/zlogout \
               --enable-zprofile=/usr/share/defaults/etc/zsh/zprofile \
               --enable-fndir=/usr/share/zsh/functions \
               --enable-scriptdir=/usr/share/zsh/scripts
build      : |
    %make
install    : |
    %make_install
    rmdir $installdir/usr/share/zsh/site-functions
    install -dm00644 $installdir/usr/share/defaults/etc/zsh/
    cp $pkgfiles/* $installdir/usr/share/defaults/etc/zsh/
check      : |
    # possible upstream issue with tests
    rm Test/P01privileged.ztst
    rm Test/D02glob.ztst
    %make check
