name       : zsh
version    : '5.9'
release    : 28
source     :
    - https://ixpeering.dl.sourceforge.net/project/zsh/zsh/5.9/zsh-5.9.tar.xz : 9b8d1ecedd5b5e81fbf1918e876752a7dd948e05c1a0dba10ab863842d45acd5
license    : MIT
summary    : The Z Shell
component  : system.utils
description: |
    Z shell (zsh) is a Unix shell that can be used as an interactive login shell and powerful command interpreter. It can be viewed as an extended Bourne shell with a number of improvements sourced from bash, tcsh, and ksh.
builddeps  :
    - pkgconfig(libcap)
    - pkgconfig(libpcre2-8)
    - gdbm-devel
    - groff # Can probably be removed in next version
setup      : |
    %apply_patches

    # Reconfigure until pcre2 patch is upstream
    %reconfigure --bindir=/usr/bin \
               --enable-cap \
               --enable-gdbm \
               --enable-multibyte \
               --enable-pcre \
               --with-tcsetpgrp \
               --enable-etcdir=/usr/share/defaults/etc/zsh \
               --enable-zshenv=/usr/share/defaults/etc/zsh/zshenv \
               --enable-zlogin=/usr/share/defaults/etc/zsh/zlogin \
               --enable-zlogout=/usr/share/defaults/etc/zsh/zlogout \
               --enable-zprofile=/usr/share/defaults/etc/zsh/zprofile \
               --enable-fndir=/usr/share/zsh/functions \
               --enable-scriptdir=/usr/share/zsh/scripts
build      : |
    %make
install    : |
    %make_install
    rmdir $installdir/usr/share/zsh/site-functions
    install -dm00644 $installdir/usr/share/defaults/etc/zsh/
    cp $pkgfiles/z* $installdir/usr/share/defaults/etc/zsh/

    # Install compat links T10615
    install -D -d -m 00755 $installdir/bin
    pushd $installdir/usr/bin
    for FILE in *; do
        ln -sv /usr/bin/$FILE $installdir/bin/$FILE
    done
    popd
check      : |
    unset LD_PRELOAD
    %make check
