name       : zsh
version    : 5.4.2
release    : 13
source     :
    - https://www.zsh.org/pub/zsh-5.4.2.tar.gz : 957bcdb2c57f64c02f673693ea5a7518ef24b6557aeb3a4ce222cefa6d74acc9
license    : MIT
summary    : The Z Shell
component  : system.utils
description: |
    Z shell (zsh) is a Unix shell that can be used as an interactive login shell and powerful command interpreter. It can be viewed as an extended Bourne shell with a number of improvements sourced from bash, tcsh, and ksh.
builddeps  :
    - pkgconfig(libcap)
    - gdbm-devel
setup      : |
    %configure --bindir=/bin \
               --enable-cap \
               --enable-multibyte \
               --enable-pcre \
               --with-tcsetpgrp
build      : |
    %make
install    : |
    %make_install
    rmdir $installdir/usr/share/zsh/site-functions
check      : |
    # Should investigate why this test fails
    rm Test/A05execution.ztst
    %make check
