name        : zsh
version     : 5.2
release     : 10
source      :
    - http://internode.dl.sourceforge.net/project/zsh/zsh/5.2/zsh-5.2.tar.xz : f17916320ffaa844bbd7ce48ceeb5945fc5f3eff64b149b4229bbfbdf3795a9d
homepage    : http://www.zsh.org
license     :
    - MIT
summary     : The Z Shell
component   : shells
description : |
    Z shell (zsh) is a Unix shell that can be used as an interactive login shell and powerful command interpreter. It can be viewed as an extended Bourne shell with a number of improvements sourced from bash, tcsh, and ksh.
setup      : |
    %configure --enable-pcre \
               --bindir=/bin \
               --with-tcsetpgrp
build      : |
    %make
install    : |
    %make_install
    rmdir $installdir/usr/share/zsh/site-functions
